---
title: "BDD ROZHACE"
subtitle: "Préparation des données"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
#  bookdown::word_document2
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Setup

## Load packages and functions

```{r}
library(tidyverse)
library(sf)
library(mapview)

# install custom functions
my_functions <- list.files(path = "../R", pattern = ".R", full.names = TRUE)
map(.x = my_functions,
    .f = source)
```

## Load data

```{r}
load(file = "../processed_data/grist_dfs.rda")
```

# Spatialisation des sites

```{r}
station_geo <- station %>% 
  st_as_sf(coords = c("X1", "Y1"), crs = st_crs(4326)) %>% 
  rename(sta_id = id)

mapview(station_geo)
```


# Nettoyage des dataframes

Il s'agit de gérer des détails de format et d'homogénéiser les *dataframes*.

## station

```{r}
station <- station %>% 
  rename(sta_id = id,
         sta_modifiee_le = Modifiee_le,
         sta_creee_par = Creee_par) %>% 
  mutate(sta_modifiee_le = sta_modifiee_le / 86400,
         sta_modifiee_le = as.Date(sta_modifiee_le))

names(station) <- tolower(names(station))
```

## operation

```{r}
operation <- operation %>% 
  rename(ope_id = id,
         sta_id = Station,
         ope_modifiee_le = Modifiee_le,
         ope_creee_par = Creee_par)

operation <- operation %>% 
  mutate(Date_operation = Date_operation / 86400,
         Date_operation = as.Date(Date_operation),
         ope_modifiee_le = ope_modifiee_le / 86400,
         ope_modifiee_le = as.Date(ope_modifiee_le),
         )

operation <- operation %>% 
  split_list_col(var_id = Operation, var_split = Strates_ripisylve_RG) %>% 
  split_list_col(var_id = Operation, var_split = Strates_ripisylve_RD) %>% 
  select(-Strates_ripisylve_RG, -Strates_ripisylve_RD) %>% 
  mutate(across(c(Nb_petits_bois, Nb_blocs),
                function(x) ifelse(x == "nan", NA, x)),
         across(c(Nb_petits_bois, Nb_blocs),
                as.numeric))

names(operation) <- tolower(names(operation))
```


## transect

```{r}
transect <- transect %>% 
  filter(!is.na(Lpb_m_)) %>% 
  mutate(Numero_du_transect = as.integer(Numero_du_transect),
         H_max_m_ = as.character(H_max_m_),
         H_max_m_ = ifelse(H_max_m_ == "NULL", NA, as.numeric(H_max_m_))) %>% 
  rename(tra_id = id,
         ope_id = Operation) %>%
  mutate(tra_ope_id_ope_date = tra_ope_id_ope_date / 86400,
         tra_ope_id_ope_date = as.Date(tra_ope_id_ope_date))

names(transect) <- tolower(names(transect))
```

## facies

```{r}
facies <- facies %>% 
  rename(fac_id = id,
         ope_id = Operation2)

names(facies) <- tolower(names(facies))
```

## Wolman

```{r}
wolman <- wolman %>% 
  rename(wol_id = id,
         ope_id = Operation2)

names(wolman) <- tolower(names(wolman))
```


## photos

```{r}
photos <- photos %>% 
  rename(pho_id = id,
         ope_id = Operation2)

names(photos) <- tolower(names(photos))
```


# Save

```{r}
save_all_dfs(file = "../processed_data/clean_dfs.rda")
```

